name = "noviq-s1"
compatibility_date = "2025-03-30"
main = "src/worker/index.js"

# Build command (if needed)
# [build]
# command = "npm run build"

# Environment variables configuration
[vars]
# Public variables


# For static assets (if needed)
# [site]
# bucket = ".next/static" 